// Generated file. Do not edit.

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitDiffScope = "staged" | "unstaged" | "commit";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabPaneSplitAxis = "horizontal" | "vertical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreePaneNode =
  | { type: "leaf"; id: string; pane_id: string }
  | {
      type: "split";
      id: string;
      axis: TabPaneSplitAxis;
      ratio: number;
      first_id: string;
      second_id: string;
    };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeTabLayout = {
  rootId: string;
  nodes: Array<WorktreePaneNode>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeTabLayoutState = {
  layout: WorktreeTabLayout;
  tabs: Array<TabInfo>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeRestoreState = {
  activeTabId?: string | null;
  focusedPaneId?: string | null;
  paneMru?: Array<string>;
  tabMruByPane?: { [key in string]: Array<string> };
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabInfo =
  | {
      type: "terminal";
      id: string;
      session_id: string;
      worktree_id: string;
      pane_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      has_notification?: boolean;
      customLabel?: string | null;
      smartLabel?: string | null;
      titleLabel?: string | null;
    }
  | {
      type: "file";
      id: string;
      session_id: string;
      worktree_id: string;
      pane_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
    }
  | {
      type: "git_diff";
      id: string;
      session_id: string;
      worktree_id: string;
      pane_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
      scope: GitDiffScope;
      original_path: string | null;
      commit_id: string | null;
    }
  | {
      type: "browser";
      id: string;
      session_id: string;
      worktree_id: string;
      pane_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      url: string;
      history: Array<string>;
      history_index: number;
    }
  | {
      type: "agent_chat";
      id: string;
      session_id: string;
      worktree_id: string;
      pane_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      conversation_id: string;
    };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = {
  id: string;
  name: string;
  path: string;
  position: number;
  git_error?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeUiMode = "hubris" | "vscode";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = {
  id: string;
  project_id: string;
  name: string;
  path: string;
  branch: string;
  source_ref: string | null;
  ui_mode: WorktreeUiMode;
  is_local: boolean;
  is_imported: boolean;
  missing_on_disk: boolean;
  position: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorScheme = "auto" | "light" | "dark";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalFontSource = "default" | "system" | "bundled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeLocationMode = "dataDir" | "repoLocalDotHubris";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = {
  colorScheme: ColorScheme;
  lightTheme: string;
  darkTheme: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = {
  fontSource: TerminalFontSource;
  systemFontFamily: string;
  bundledFont: string;
  fontSize: number;
  smartTabNaming: boolean;
  escapeSequenceTitles: boolean;
  sendKeybindingsToShell: boolean;
  clientScrollbackRows: number;
  serverScrollbackBytes: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettings = {
  lightEditorTheme: string;
  darkEditorTheme: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettingsPatch = {
  lightEditorTheme?: string | null;
  darkEditorTheme?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeSettings = { locationMode: WorktreeLocationMode };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeRuntimeKind = "vscodeCli" | "codeServer";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeSettings = { runtime: VscodeRuntimeKind };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported chat providers.
 */
export type ChatProvider = "codex";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit permissions preset override. `None` means use Codex defaults.
 */
export type ChatPermissionMode = "full_access";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported reasoning-effort values exposed by Codex model selection.
 */
export type ChatReasoningEffort =
  | "none"
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted message role for a conversation transcript item.
 */
export type ChatMessageRole = "user" | "assistant";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted message lifecycle state.
 */
export type ChatMessageStatus =
  | "pending"
  | "streaming"
  | "completed"
  | "interrupted"
  | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted run lifecycle state.
 */
export type ChatRunStatus =
  | "starting"
  | "running"
  | "completed"
  | "interrupted"
  | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted Codex turn lifecycle state.
 */
export type ChatTurnStatus =
  | "starting"
  | "running"
  | "completed"
  | "interrupted"
  | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized Codex item kind persisted for future timeline rendering.
 */
export type ChatItemKind = "agent_message" | "reasoning" | "unknown";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted Codex item lifecycle state.
 */
export type ChatItemStatus = "started" | "streaming" | "completed" | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * In-memory runtime lifecycle state for a live Codex app-server process.
 */
export type ChatRuntimeLifecycle =
  | "stopped"
  | "starting"
  | "ready"
  | "running"
  | "stopping"
  | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared Codex app-server process lifecycle pushed over SSE.
 */
export type ChatAppServerLifecycle =
  | "stopped"
  | "starting"
  | "initializing"
  | "ready"
  | "stopping"
  | "fatal";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host-scoped Codex app-server status.
 */
export type ChatAppServerStatus = {
  lifecycle: ChatAppServerLifecycle;
  lastError?: string | null;
  updatedAt: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-conversation Codex thread stream resume state.
 */
export type ChatThreadStreamResumeState =
  | "not_started"
  | "needs_resume"
  | "resuming"
  | "resumed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live stream status for one Codex thread.
 */
export type ChatThreadStreamStatus = {
  conversationId: string;
  sessionId: string;
  projectId: string;
  worktreeId: string;
  resumeState: ChatThreadStreamResumeState;
  lifecycle: ChatRuntimeLifecycle;
  activeRunId?: string | null;
  activeMessageId?: string | null;
  providerThreadId?: string | null;
  inactiveDeadlineAt?: number | null;
  lastError?: string | null;
  updatedAt: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reasoning-effort option supported by a Codex model.
 */
export type ChatModelReasoningEffortOption = {
  reasoningEffort: ChatReasoningEffort;
  description: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable Codex model exposed by app-server.
 */
export type ChatModelOption = {
  id: string;
  model: string;
  displayName: string;
  description: string;
  isDefault: boolean;
  hidden: boolean;
  defaultReasoningEffort: ChatReasoningEffort;
  supportedReasoningEfforts: Array<ChatModelReasoningEffortOption>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation-level model preferences that apply to future turns.
 */
export type ChatConversationSettingsPatch = {
  selectedModel: string | null;
  selectedEffort: ChatReasoningEffort | null;
  selectedPermissionMode: ChatPermissionMode | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted summary for a conversation list row.
 */
export type ChatConversationSummary = {
  id: string;
  sessionId: string;
  projectId: string;
  worktreeId: string;
  provider: ChatProvider;
  providerThreadId?: string | null;
  title: string;
  createdAt: number;
  updatedAt: number;
  lastActivityAt: number;
  lastMessageAt?: number | null;
  openTabId?: string | null;
  selectedModel?: string | null;
  selectedEffort?: ChatReasoningEffort | null;
  selectedPermissionMode?: ChatPermissionMode | null;
  lastRunState: ChatRunStatus;
  lastError?: string | null;
  revision: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted transcript message.
 */
export type ChatMessage = {
  id: string;
  conversationId: string;
  turnId?: string | null;
  itemId?: string | null;
  providerTurnId?: string | null;
  providerItemId?: string | null;
  role: ChatMessageRole;
  status: ChatMessageStatus;
  contentText: string;
  reasoningText: string;
  sequence: number;
  createdAt: number;
  updatedAt: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted run summary.
 */
export type ChatRun = {
  id: string;
  conversationId: string;
  turnId?: string | null;
  providerTurnId?: string | null;
  status: ChatRunStatus;
  startedAt: number;
  finishedAt?: number | null;
  errorMessage?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted provider turn metadata for a chat conversation.
 */
export type ChatTurn = {
  id: string;
  conversationId: string;
  runId: string;
  userMessageId: string;
  assistantMessageId: string;
  providerTurnId?: string | null;
  status: ChatTurnStatus;
  startedAt: number;
  completedAt?: number | null;
  errorMessage?: string | null;
  createdAt: number;
  updatedAt: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted provider item metadata for a chat conversation.
 */
export type ChatItem = {
  id: string;
  conversationId: string;
  turnId?: string | null;
  providerTurnId?: string | null;
  providerItemId?: string | null;
  kind: ChatItemKind;
  status: ChatItemStatus;
  role?: ChatMessageRole | null;
  sequence: number;
  title?: string | null;
  summary?: string | null;
  metadataJson: string;
  createdAt: number;
  updatedAt: number;
  completedAt?: number | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full chat detail payload used to hydrate an open chat tab.
 */
export type ChatConversationDetail = {
  conversation: ChatConversationSummary;
  messages: Array<ChatMessage>;
  turns: Array<ChatTurn>;
  items: Array<ChatItem>;
  latestRun?: ChatRun | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared runtime summary pushed over SSE.
 */
export type ChatRuntimeStatus = {
  conversationId: string;
  sessionId: string;
  projectId: string;
  worktreeId: string;
  lifecycle: ChatRuntimeLifecycle;
  activeRunId?: string | null;
  activeMessageId?: string | null;
  providerThreadId?: string | null;
  lastError?: string | null;
  updatedAt: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chat settings owned by the backend.
 */
export type ChatSettings = { idleTimeoutMinutes: number };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
  appearance: AppearanceSettings;
  terminal: TerminalSettings;
  editor: EditorSettings;
  worktree: WorktreeSettings;
  vscode: VscodeSettings;
  chat: ChatSettings;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatusKind = "ok" | "invalidFile";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatus = {
  kind: SettingsStatusKind;
  writesBlocked: boolean;
  message: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsState = {
  settings: Settings;
  generation: string;
  status: SettingsStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeybindingEntry = {
  key: string;
  command?: string | null;
  args?: JsonValue | null;
  when?: string | null;
  disabled: boolean;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeybindingsStatusKind = "ok" | "invalidFile";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeybindingsStatus = {
  kind: KeybindingsStatusKind;
  writesBlocked: boolean;
  message: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeybindingsState = {
  keybindings: Array<KeybindingEntry>;
  generation: string;
  status: KeybindingsStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeInstallPhase =
  | "preparing"
  | "downloading"
  | "extracting"
  | "cleaning"
  | "starting";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeInstallProgress = {
  phase: VscodeInstallPhase;
  percent: number;
  downloadedBytes: bigint | null;
  totalBytes: bigint | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeLatestCheck = {
  latestVersion: string | null;
  updateAvailable: boolean;
  checkedAt: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeProcessStatus =
  | "running"
  | "stopped"
  | "starting"
  | "stopping"
  | "installing"
  | "error";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeRuntimeStatus = {
  supported: boolean;
  installedVersion: string | null;
  processStatus: VscodeProcessStatus;
  latest: VscodeLatestCheck | null;
  installProgress: VscodeInstallProgress | null;
  message: string | null;
  activeTaskId: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeStatus = {
  selectedRuntime: VscodeRuntimeKind;
  codeServer: VscodeRuntimeStatus;
  vscodeCli: VscodeRuntimeStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessLifecycleStateValue =
  | "stopped"
  | "starting"
  | "running"
  | "stopping"
  | "exited"
  | "error";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessExitInfo = {
  code: number | null;
  signal: number | null;
  finishedAt: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessStatus = {
  id: string;
  kind: string;
  lifecycleState: ManagedProcessLifecycleStateValue;
  pid: number | null;
  startedAt: string | null;
  lastExit: ManagedProcessExitInfo | null;
  lastError: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskState =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "rollingBack"
  | "rolledBack"
  | "rollbackFailed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepState =
  | "pending"
  | "running"
  | "skipped"
  | "succeeded"
  | "failed"
  | "rollingBack"
  | "rolledBack"
  | "rollbackFailed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskInputFieldKind = "string" | "boolean";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskDefinitionInputField = {
  name: string;
  title: string;
  description: string | null;
  required: boolean;
  kind: TaskInputFieldKind;
  enumValues: Array<string>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskDefinition = {
  name: string;
  title: string;
  description: string | null;
  broadcastUpdates: boolean;
  inputFields: Array<TaskDefinitionInputField>;
  steps: Array<TaskStepDefinition>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepDefinition = { id: string; title: string; weight: number };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepStatus = {
  id: string;
  name: string;
  state: TaskStepState;
  progressPercent: number;
  error: string | null;
  rollbackError: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskInvocationStatus = {
  id: string;
  definitionName: string;
  title: string;
  status: TaskState;
  statusText: string | null;
  progressPercent: number;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  scopeKey: string | null;
  failureMessage: string | null;
  broadcastUpdates: boolean;
  steps: Array<TaskStepStatus>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskUpdated = { task: TaskInvocationStatus };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRemoved = { id: string };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventKind =
  | {
      type: "snapshot";
      data: {
        tabs: Array<TabInfo>;
        tab_layouts: { [key in string]: WorktreeTabLayout };
        worktree_restore_state: { [key in string]: WorktreeRestoreState };
        chat_app_server: ChatAppServerStatus;
        chat_conversations: Array<ChatConversationSummary>;
        chat_runtimes: Array<ChatRuntimeStatus>;
        chat_thread_streams: Array<ChatThreadStreamStatus>;
        projects: Array<Project>;
        worktrees: { [key in string]: Array<Worktree> };
        project_errors: { [key in string]: string };
        settings: Settings;
        settings_generation: string;
        settings_status: SettingsStatus;
        keybindings: Array<KeybindingEntry>;
        keybindings_generation: string;
        keybindings_status: KeybindingsStatus;
        vscode: VscodeStatus;
        managed_processes: Array<ManagedProcessStatus>;
        tasks: Array<TaskInvocationStatus>;
      };
    }
  | { type: "tab_created"; data: { session_id: string; tab: TabInfo } }
  | { type: "tab_closed"; data: { session_id: string; tab_id: string } }
  | { type: "tab_updated"; data: { session_id: string; tab: TabInfo } }
  | {
      type: "tabs_reordered";
      data: { session_id: string; worktree_id: string; tabs: Array<TabInfo> };
    }
  | {
      type: "worktree_tab_layout_updated";
      data: { worktree_id: string; state: WorktreeTabLayoutState };
    }
  | { type: "project_added"; data: Project }
  | { type: "project_removed"; data: { project_id: string } }
  | { type: "project_updated"; data: Project }
  | { type: "projects_reordered"; data: Array<Project> }
  | { type: "worktree_created"; data: Worktree }
  | {
      type: "worktree_deleted";
      data: { project_id: string; worktree_id: string };
    }
  | {
      type: "worktrees_reordered";
      data: { project_id: string; worktrees: Array<Worktree> };
    }
  | {
      type: "project_worktrees_updated";
      data: {
        project_id: string;
        worktrees: Array<Worktree>;
        git_error: string | null;
      };
    }
  | {
      type: "worktree_files_updated";
      data: {
        project_id: string;
        worktree_id: string;
        generation: number;
        changed_paths: Array<string>;
        listing_paths: Array<string>;
      };
    }
  | {
      type: "worktree_git_status_updated";
      data: { project_id: string; worktree_id: string; generation: number };
    }
  | { type: "settings_updated"; data: SettingsState }
  | { type: "keybindings_updated"; data: KeybindingsState }
  | { type: "vscode_updated"; data: VscodeStatus }
  | { type: "managed_process_updated"; data: ManagedProcessStatus }
  | { type: "task_updated"; data: TaskUpdated }
  | { type: "task_removed"; data: TaskRemoved }
  | {
      type: "chat_conversation_created";
      data: { session_id: string; conversation: ChatConversationSummary };
    }
  | {
      type: "chat_conversation_updated";
      data: { session_id: string; conversation: ChatConversationSummary };
    }
  | {
      type: "chat_runtime_updated";
      data: { session_id: string; runtime: ChatRuntimeStatus };
    }
  | {
      type: "chat_app_server_updated";
      data: { app_server: ChatAppServerStatus };
    }
  | {
      type: "chat_thread_stream_updated";
      data: { session_id: string; stream: ChatThreadStreamStatus };
    }
  | {
      type: "chat_message_delta";
      data: {
        session_id: string;
        conversation_id: string;
        message_id: string;
        delta: string;
        revision: bigint;
      };
    }
  | {
      type: "chat_message_updated";
      data: {
        session_id: string;
        conversation_id: string;
        message: ChatMessage;
      };
    }
  | {
      type: "chat_run_updated";
      data: { session_id: string; conversation_id: string; run: ChatRun };
    }
  | {
      type: "chat_turn_updated";
      data: { session_id: string; conversation_id: string; turn: ChatTurn };
    }
  | {
      type: "chat_item_updated";
      data: { session_id: string; conversation_id: string; item: ChatItem };
    };
