// Generated file. Do not edit.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitDiffScope = "staged" | "unstaged" | "commit";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabInfo =
  | {
      type: "terminal";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      has_notification?: boolean;
      customLabel?: string | null;
      processLabel?: string | null;
      titleLabel?: string | null;
    }
  | {
      type: "file";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
    }
  | {
      type: "git_diff";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
      scope: GitDiffScope;
      original_path: string | null;
      commit_id: string | null;
    }
  | {
      type: "browser";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      url: string;
      history: Array<string>;
      history_index: number;
    };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = {
  id: string;
  name: string;
  path: string;
  position: number;
  git_error?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeUiMode = "hubris" | "vscode";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = {
  id: string;
  project_id: string;
  name: string;
  path: string;
  branch: string;
  source_ref: string | null;
  ui_mode: WorktreeUiMode;
  is_local: boolean;
  is_imported: boolean;
  missing_on_disk: boolean;
  position: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorScheme = "auto" | "light" | "dark";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalFontSource = "default" | "system" | "bundled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalTabLabelMode = "numbered" | "process" | "title";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeLocationMode = "dataDir" | "repoLocalDotHubris";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = {
  colorScheme: ColorScheme;
  lightTheme: string;
  darkTheme: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = {
  fontSource: TerminalFontSource;
  systemFontFamily: string;
  bundledFont: string;
  fontSize: number;
  tabLabelMode: TerminalTabLabelMode;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettings = {
  lightEditorTheme: string;
  darkEditorTheme: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettingsPatch = {
  lightEditorTheme?: string | null;
  darkEditorTheme?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeSettings = { locationMode: WorktreeLocationMode };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeRuntimeKind = "vscodeCli" | "codeServer";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeSettings = { runtime: VscodeRuntimeKind };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
  appearance: AppearanceSettings;
  terminal: TerminalSettings;
  editor: EditorSettings;
  worktree: WorktreeSettings;
  vscode: VscodeSettings;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatusKind = "ok" | "invalidFile";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatus = {
  kind: SettingsStatusKind;
  writesBlocked: boolean;
  message: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsState = {
  settings: Settings;
  generation: string;
  status: SettingsStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeInstallPhase =
  | "preparing"
  | "downloading"
  | "extracting"
  | "cleaning"
  | "starting";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeInstallProgress = {
  phase: VscodeInstallPhase;
  percent: number;
  downloadedBytes: bigint | null;
  totalBytes: bigint | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeLatestCheck = {
  latestVersion: string | null;
  updateAvailable: boolean;
  checkedAt: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeProcessStatus =
  | "running"
  | "stopped"
  | "starting"
  | "stopping"
  | "installing"
  | "error";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeRuntimeStatus = {
  supported: boolean;
  installedVersion: string | null;
  processStatus: VscodeProcessStatus;
  latest: VscodeLatestCheck | null;
  installProgress: VscodeInstallProgress | null;
  message: string | null;
  activeTaskId: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VscodeStatus = {
  selectedRuntime: VscodeRuntimeKind;
  codeServer: VscodeRuntimeStatus;
  vscodeCli: VscodeRuntimeStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessLifecycleStateValue =
  | "stopped"
  | "starting"
  | "running"
  | "stopping"
  | "exited"
  | "error";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessExitInfo = {
  code: number | null;
  signal: number | null;
  finishedAt: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedProcessStatus = {
  id: string;
  kind: string;
  lifecycleState: ManagedProcessLifecycleStateValue;
  pid: number | null;
  startedAt: string | null;
  lastExit: ManagedProcessExitInfo | null;
  lastError: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskState =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "rollingBack"
  | "rolledBack"
  | "rollbackFailed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepState =
  | "pending"
  | "running"
  | "skipped"
  | "succeeded"
  | "failed"
  | "rollingBack"
  | "rolledBack"
  | "rollbackFailed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskInputFieldKind = "string" | "boolean";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskDefinitionInputField = {
  name: string;
  title: string;
  description: string | null;
  required: boolean;
  kind: TaskInputFieldKind;
  enumValues: Array<string>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskDefinition = {
  name: string;
  title: string;
  description: string | null;
  broadcastUpdates: boolean;
  inputFields: Array<TaskDefinitionInputField>;
  steps: Array<TaskStepDefinition>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepDefinition = { id: string; title: string; weight: number };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStepStatus = {
  id: string;
  name: string;
  state: TaskStepState;
  progressPercent: number;
  error: string | null;
  rollbackError: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskInvocationStatus = {
  id: string;
  definitionName: string;
  title: string;
  status: TaskState;
  statusText: string | null;
  progressPercent: number;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  scopeKey: string | null;
  failureMessage: string | null;
  broadcastUpdates: boolean;
  steps: Array<TaskStepStatus>;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskUpdated = { task: TaskInvocationStatus };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRemoved = { id: string };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventKind =
  | {
      type: "snapshot";
      data: {
        tabs: Array<TabInfo>;
        projects: Array<Project>;
        worktrees: { [key in string]: Array<Worktree> };
        project_errors: { [key in string]: string };
        settings: Settings;
        settings_generation: string;
        settings_status: SettingsStatus;
        vscode: VscodeStatus;
        managed_processes: Array<ManagedProcessStatus>;
        tasks: Array<TaskInvocationStatus>;
      };
    }
  | { type: "tab_created"; data: { session_id: string; tab: TabInfo } }
  | { type: "tab_closed"; data: { session_id: string; tab_id: string } }
  | { type: "tab_updated"; data: { session_id: string; tab: TabInfo } }
  | {
      type: "tabs_reordered";
      data: { session_id: string; worktree_id: string; tabs: Array<TabInfo> };
    }
  | { type: "project_added"; data: Project }
  | { type: "project_removed"; data: { project_id: string } }
  | { type: "project_updated"; data: Project }
  | { type: "projects_reordered"; data: Array<Project> }
  | { type: "worktree_created"; data: Worktree }
  | {
      type: "worktree_deleted";
      data: { project_id: string; worktree_id: string };
    }
  | {
      type: "worktrees_reordered";
      data: { project_id: string; worktrees: Array<Worktree> };
    }
  | {
      type: "project_worktrees_updated";
      data: {
        project_id: string;
        worktrees: Array<Worktree>;
        git_error: string | null;
      };
    }
  | {
      type: "worktree_files_updated";
      data: {
        project_id: string;
        worktree_id: string;
        generation: number;
        changed_paths: Array<string>;
        listing_paths: Array<string>;
      };
    }
  | {
      type: "worktree_git_status_updated";
      data: { project_id: string; worktree_id: string; generation: number };
    }
  | { type: "settings_updated"; data: SettingsState }
  | { type: "vscode_updated"; data: VscodeStatus }
  | { type: "managed_process_updated"; data: ManagedProcessStatus }
  | { type: "task_updated"; data: TaskUpdated }
  | { type: "task_removed"; data: TaskRemoved };
