export const WORKTREE_RIGHT_SIDEBAR_ALL_FILES_TAB = "all-files";
export const WORKTREE_RIGHT_SIDEBAR_CHANGES_TAB = "changes";

export type WorktreeRightSidebarTabId =
  | typeof WORKTREE_RIGHT_SIDEBAR_ALL_FILES_TAB
  | typeof WORKTREE_RIGHT_SIDEBAR_CHANGES_TAB;

export const DEFAULT_WORKTREE_RIGHT_SIDEBAR_TAB =
  WORKTREE_RIGHT_SIDEBAR_ALL_FILES_TAB;
