export const WORKTREE_RIGHT_SIDEBAR_GIT_STATUS_PANEL = "git-status";

export type WorktreeRightSidebarPanelId =
  typeof WORKTREE_RIGHT_SIDEBAR_GIT_STATUS_PANEL;

export const DEFAULT_WORKTREE_RIGHT_SIDEBAR_PANEL =
  WORKTREE_RIGHT_SIDEBAR_GIT_STATUS_PANEL;
