import type { HubrisTheme } from './types';

export const catppuccinLatte: HubrisTheme = {
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  type: 'light',
  builtin: true,
  colors: {
    foreground: '#4c4f69',
    focusBorder: '#7287fd',
    errorForeground: '#d20f39',
    'editor.background': '#eff1f5',
    'editor.foreground': '#4c4f69',
    'editorWidget.background': '#e6e9ef',
    'editorWidget.foreground': '#4c4f69',
    'editorGroupHeader.tabsBackground': '#e6e9ef',
    'sideBar.background': '#e6e9ef',
    'sideBar.foreground': '#4c4f69',
    'sideBar.border': '#ccd0da',
    'list.activeSelectionBackground': '#bcc0cc',
    'list.activeSelectionForeground': '#4c4f69',
    'list.hoverBackground': '#ccd0da',
    'list.hoverForeground': '#4c4f69',
    'tab.activeBackground': '#eff1f5',
    'tab.activeForeground': '#4c4f69',
    'tab.inactiveBackground': '#e6e9ef',
    'tab.inactiveForeground': '#8c8fa1',
    'tab.border': '#ccd0da',
    'panel.border': '#ccd0da',
    'editorGroup.border': '#ccd0da',
    'input.background': '#ccd0da',
    'button.background': '#7287fd',
    'button.foreground': '#dce0e8',
    'button.secondaryBackground': '#ccd0da',
    'button.secondaryForeground': '#4c4f69',
    'terminal.background': '#eff1f5',
    'terminal.foreground': '#4c4f69',
    'terminalCursor.foreground': '#dc8a78',
    'terminal.selectionBackground': '#acb0be80',
    'terminal.ansiBlack': '#5c5f77',
    'terminal.ansiRed': '#d20f39',
    'terminal.ansiGreen': '#40a02b',
    'terminal.ansiYellow': '#df8e1d',
    'terminal.ansiBlue': '#1e66f5',
    'terminal.ansiMagenta': '#8839ef',
    'terminal.ansiCyan': '#179299',
    'terminal.ansiWhite': '#acb0be',
    'terminal.ansiBrightBlack': '#6c6f85',
    'terminal.ansiBrightRed': '#d20f39',
    'terminal.ansiBrightGreen': '#40a02b',
    'terminal.ansiBrightYellow': '#df8e1d',
    'terminal.ansiBrightBlue': '#1e66f5',
    'terminal.ansiBrightMagenta': '#8839ef',
    'terminal.ansiBrightCyan': '#179299',
    'terminal.ansiBrightWhite': '#bcc0cc',
  },
};

export const catppuccinMocha: HubrisTheme = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  type: 'dark',
  builtin: true,
  colors: {
    foreground: '#cdd6f4',
    focusBorder: '#b4befe',
    errorForeground: '#f38ba8',
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editorWidget.background': '#313244',
    'editorWidget.foreground': '#cdd6f4',
    'editorGroupHeader.tabsBackground': '#181825',
    'sideBar.background': '#181825',
    'sideBar.foreground': '#cdd6f4',
    'sideBar.border': '#313244',
    'list.activeSelectionBackground': '#45475a',
    'list.activeSelectionForeground': '#cdd6f4',
    'list.hoverBackground': '#313244',
    'list.hoverForeground': '#cdd6f4',
    'tab.activeBackground': '#1e1e2e',
    'tab.activeForeground': '#cdd6f4',
    'tab.inactiveBackground': '#181825',
    'tab.inactiveForeground': '#6c7086',
    'tab.border': '#313244',
    'panel.border': '#313244',
    'editorGroup.border': '#313244',
    'input.background': '#313244',
    'button.background': '#b4befe',
    'button.foreground': '#11111b',
    'button.secondaryBackground': '#45475a',
    'button.secondaryForeground': '#cdd6f4',
    'terminal.background': '#1e1e2e',
    'terminal.foreground': '#cdd6f4',
    'terminalCursor.foreground': '#f5e0dc',
    'terminal.selectionBackground': '#585b7066',
    'terminal.ansiBlack': '#45475a',
    'terminal.ansiRed': '#f38ba8',
    'terminal.ansiGreen': '#a6e3a1',
    'terminal.ansiYellow': '#f9e2af',
    'terminal.ansiBlue': '#89b4fa',
    'terminal.ansiMagenta': '#f5c2e7',
    'terminal.ansiCyan': '#94e2d5',
    'terminal.ansiWhite': '#bac2de',
    'terminal.ansiBrightBlack': '#585b70',
    'terminal.ansiBrightRed': '#f38ba8',
    'terminal.ansiBrightGreen': '#a6e3a1',
    'terminal.ansiBrightYellow': '#f9e2af',
    'terminal.ansiBrightBlue': '#89b4fa',
    'terminal.ansiBrightMagenta': '#f5c2e7',
    'terminal.ansiBrightCyan': '#94e2d5',
    'terminal.ansiBrightWhite': '#a6adc8',
  },
};

export const builtinThemes: HubrisTheme[] = [catppuccinLatte, catppuccinMocha];
