/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["event_stream"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_files"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the generated OpenAPI document as JSON. */
    get: operations["openapi_json"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_projects"];
    put?: never;
    post: operations["add_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_projects"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_project"];
    options?: never;
    head?: never;
    patch: operations["update_project"];
    trace?: never;
  };
  "/api/projects/{id}/worktrees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktrees"];
    put?: never;
    post: operations["create_project_worktree"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_project_worktrees"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/start-points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktree_start_points"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_project_worktree"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktree_files"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/files/rename": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rename_project_worktree_file"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_git_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/commits/{commit_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_commit_details"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/discard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["discard_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/stage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["stage_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/unstage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["unstage_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/settings */
    get: operations["get_settings"];
    /** PUT /api/settings — full replace */
    put: operations["put_settings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** PATCH /api/settings — partial update */
    patch: operations["patch_settings"];
    trace?: never;
  };
  "/api/tabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_tabs"];
    put?: never;
    post: operations["create_tab"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tabs/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_tabs"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tabs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_tab"];
    options?: never;
    head?: never;
    patch: operations["update_tab"];
    trace?: never;
  };
  "/api/terminal/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ws_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddProjectRequest: {
      path: string;
    };
    AppearanceSettings: {
      colorScheme?: components["schemas"]["ColorScheme"];
      darkTheme?: string;
      lightTheme?: string;
    };
    AppearanceSettingsPatch: {
      colorScheme?: null | components["schemas"]["ColorScheme"];
      darkTheme?: string | null;
      lightTheme?: string | null;
    };
    ClientControlMessage: {
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      /** @enum {string} */
      type: "resize";
      visible: boolean;
    };
    /** @enum {string} */
    ColorScheme: "auto" | "light" | "dark";
    CreateTabRequest: {
      worktree_id: string;
    };
    CreateWorktreeRequest: {
      branch: string;
      source_ref?: string | null;
      start_point?: string | null;
    };
    DirEntry: {
      is_git_repo: boolean;
      name: string;
    };
    GitCommitDetailsResponse: {
      author: components["schemas"]["GitCommitPerson"];
      committer: components["schemas"]["GitCommitPerson"];
      files: components["schemas"]["GitFileChange"][];
      id: string;
      message: string;
      short_id: string;
      summary: string;
    };
    GitCommitPerson: {
      date: string;
      email: string;
      name: string;
    };
    GitCommitSummary: {
      id: string;
      short_id: string;
      summary: string;
    };
    GitFileChange: {
      change_type: components["schemas"]["GitFileChangeType"];
      original_path?: string | null;
      path: string;
    };
    /** @enum {string} */
    GitFileChangeType:
      | "added"
      | "copied"
      | "renamed"
      | "conflict"
      | "modified"
      | "deleted"
      | "typechange"
      | "untracked";
    ListFilesResponse: {
      /** @description Subdirectories within `path`. */
      entries: components["schemas"]["DirEntry"][];
      /** @description User's home directory (for quick-nav in UI). */
      home_dir?: string | null;
      /** @description Canonical absolute path of the listed directory. */
      path: string;
    };
    ListWorktreeFilesResponse: {
      entries: components["schemas"]["WorktreeFileEntry"][];
      /** Format: int32 */
      generation: number;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    ListWorktreeStartPointsResponse: {
      default_start_point?: string | null;
      git_error?: string | null;
      start_points: components["schemas"]["StartPoint"][];
    };
    ListWorktreesResponse: {
      git_error?: string | null;
      worktrees: components["schemas"]["Worktree"][];
    };
    Project: {
      git_error?: string | null;
      id: string;
      name: string;
      path: string;
      /** Format: double */
      position?: number;
    };
    RenameWorktreeFileRequest: {
      /** @description New basename for the file or directory. */
      new_name: string;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    RenameWorktreeFileResponse: {
      /** @description Updated relative path from the worktree root. */
      path: string;
    };
    ReorderProjectsRequest: {
      project_ids: string[];
    };
    ReorderTabsRequest: {
      tab_ids: string[];
      worktree_id: string;
    };
    ReorderWorktreesRequest: {
      worktree_ids: string[];
    };
    ServerControlMessage:
      | {
          /** Format: int64 */
          byte_offset: number;
          /** Format: int32 */
          cols: number;
          data_lost: boolean;
          /** Format: int32 */
          rows: number;
          snapshot: boolean;
          /** @enum {string} */
          type: "attached";
        }
      | {
          /** Format: int32 */
          cols: number;
          /** Format: int32 */
          rows: number;
          /** @enum {string} */
          type: "pty_resized";
        }
      | {
          /** @enum {string} */
          type: "tab_closed";
        };
    Settings: {
      appearance?: components["schemas"]["AppearanceSettings"];
      terminal?: components["schemas"]["TerminalSettings"];
      worktree?: components["schemas"]["WorktreeSettings"];
    };
    SettingsPatch: {
      appearance?: null | components["schemas"]["AppearanceSettingsPatch"];
      terminal?: null | components["schemas"]["TerminalSettingsPatch"];
      worktree?: null | components["schemas"]["WorktreeSettingsPatch"];
    };
    SettingsState: {
      generation: string;
      settings: components["schemas"]["Settings"];
      status: components["schemas"]["SettingsStatus"];
    };
    SettingsStatus: {
      kind: components["schemas"]["SettingsStatusKind"];
      message?: string | null;
      writesBlocked: boolean;
    };
    /** @enum {string} */
    SettingsStatusKind: "ok" | "invalidFile";
    StartPoint: {
      local_ref?: string | null;
      remote_refs: string[];
      sha: string;
      value: string;
    };
    /**
     * @description Serializable tab metadata. Sent to clients via REST
     *     and SSE.
     */
    TabInfo: {
      /** Format: int64 */
      created_at: number;
      id: string;
      label: string;
      /** Format: double */
      position: number;
      session_id: string;
      type: string;
      worktree_id: string;
    };
    /** @enum {string} */
    TerminalFontSource: "default" | "system" | "bundled";
    TerminalSettings: {
      bundledFont?: string;
      /** Format: int32 */
      fontSize?: number;
      fontSource?: components["schemas"]["TerminalFontSource"];
      systemFontFamily?: string;
    };
    TerminalSettingsPatch: {
      bundledFont?: string | null;
      /** Format: int32 */
      fontSize?: number | null;
      fontSource?: null | components["schemas"]["TerminalFontSource"];
      systemFontFamily?: string | null;
    };
    UpdateProjectRequest: {
      name?: string | null;
    };
    UpdateTabRequest: {
      label?: string | null;
      /** Format: double */
      position?: number | null;
    };
    Worktree: {
      branch: string;
      id: string;
      is_local: boolean;
      missing_on_disk?: boolean;
      name: string;
      path: string;
      /** Format: double */
      position: number;
      project_id: string;
      source_ref?: string | null;
    };
    WorktreeFileEntry: {
      kind: components["schemas"]["WorktreeFileKind"];
      name: string;
      path: string;
    };
    /** @enum {string} */
    WorktreeFileKind: "directory" | "file";
    WorktreeGitPathActionRequest: {
      /** @description Original relative path for rename/copy actions. */
      original_path?: string | null;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    WorktreeGitStatusResponse: {
      ahead_commits: components["schemas"]["GitCommitSummary"][];
      ahead_count: number;
      comparison_available: boolean;
      comparison_error?: string | null;
      /** Format: int32 */
      generation: number;
      source_ref?: string | null;
      staged_files: components["schemas"]["GitFileChange"][];
      unstaged_files: components["schemas"]["GitFileChange"][];
    };
    /** @enum {string} */
    WorktreeLocationMode: "dataDir" | "repoLocalDotHubris";
    WorktreeSettings: {
      locationMode?: components["schemas"]["WorktreeLocationMode"];
    };
    WorktreeSettingsPatch: {
      locationMode?: null | components["schemas"]["WorktreeLocationMode"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  event_stream: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent event stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_files: {
    parameters: {
      query?: {
        /** @description Directory to list. Defaults to home dir. */
        path?: string;
        /** @description Whether to include dotfiles. Defaults to false. */
        show_hidden?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory listing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListFilesResponse"];
        };
      };
      /** @description Path is not a directory */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Directory not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  openapi_json: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenAPI document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  add_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddProjectRequest"];
      };
    };
    responses: {
      /** @description Project already exists */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Project created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Invalid path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderProjectsRequest"];
      };
    };
    responses: {
      /** @description Projects reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
      /** @description Invalid order payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project: {
    parameters: {
      query?: {
        force?: boolean;
        delete_managed_worktrees?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid project path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project has dirty or busy managed worktrees */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectRequest"];
      };
    };
    responses: {
      /** @description Project updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project worktrees */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreesResponse"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_project_worktree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorktreeRequest"];
      };
    };
    responses: {
      /** @description Worktree created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree creation conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderWorktreesRequest"];
      };
    };
    responses: {
      /** @description Worktrees reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"][];
        };
      };
      /** @description Invalid reorder payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktree_start_points: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Candidate worktree start points */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreeStartPointsResponse"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project_worktree: {
    parameters: {
      query?: {
        force?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Worktree removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid worktree request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree has uncommitted changes */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktree_files: {
    parameters: {
      query?: {
        /** @description Relative path from the worktree root. Empty means root. */
        path?: string;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List immediate children for a worktree-relative directory */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreeFilesResponse"];
        };
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or directory not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rename_project_worktree_file: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameWorktreeFileRequest"];
      };
    };
    responses: {
      /** @description Rename a file or directory within the worktree */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RenameWorktreeFileResponse"];
        };
      };
      /** @description Invalid relative path or new name */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Target path already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_git_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Git status for a worktree */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorktreeGitStatusResponse"];
        };
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_commit_details: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
        /** @description Commit SHA */
        commit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit details for a worktree commit */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GitCommitDetailsResponse"];
        };
      };
      /** @description Project, worktree, or commit not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  discard_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Worktree changes discarded for the path */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  stage_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Path staged */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unstage_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Path unstaged */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      /** @description Settings saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Settings file is invalid on disk */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description Settings patched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Settings file is invalid on disk */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_tabs: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List tabs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"][];
        };
      };
    };
  };
  create_tab: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTabRequest"];
      };
    };
    responses: {
      /** @description Tab created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"];
        };
      };
      /** @description Worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_tabs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderTabsRequest"];
      };
    };
    responses: {
      /** @description Tabs reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"][];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tab removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTabRequest"];
      };
    };
    responses: {
      /** @description Tab updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"];
        };
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ws_handler: {
    parameters: {
      query: {
        tab_id: string;
        /**
         * @description Byte offset for resumable reconnection. When
         *     present, the server only replays scrollback bytes
         *     the client missed.
         */
        resume_from?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket upgraded */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
