/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['event_stream'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_files'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the generated OpenAPI document as JSON. */
    get: operations['openapi_json'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_projects'];
    put?: never;
    post: operations['add_project'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['reorder_projects'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['delete_project'];
    options?: never;
    head?: never;
    patch: operations['update_project'];
    trace?: never;
  };
  '/api/projects/{id}/worktrees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_project_worktrees'];
    put?: never;
    post: operations['create_project_worktree'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/worktrees/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['reorder_project_worktrees'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/worktrees/start-points': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_project_worktree_start_points'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{id}/worktrees/{worktree_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['delete_project_worktree'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/settings */
    get: operations['get_settings'];
    /** PUT /api/settings — full replace */
    put: operations['save_settings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tabs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_tabs'];
    put?: never;
    post: operations['create_tab'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tabs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['delete_tab'];
    options?: never;
    head?: never;
    patch: operations['update_tab'];
    trace?: never;
  };
  '/api/terminal/ws': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ws_handler'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/themes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/themes — list user theme metadata */
    get: operations['list_themes'];
    put?: never;
    /** POST /api/themes — upload a new theme */
    post: operations['create_theme'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/themes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/themes/:id — get full theme */
    get: operations['get_theme'];
    put?: never;
    post?: never;
    /** DELETE /api/themes/:id — remove a user theme */
    delete: operations['delete_theme'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddProjectRequest: {
      path: string;
    };
    AppearanceSettings: {
      colorScheme?: string;
      darkTheme?: string;
      lightTheme?: string;
    };
    ClientControlMessage: {
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      /** @enum {string} */
      type: 'resize';
    };
    CreateTabRequest: {
      worktree_id: string;
    };
    CreateWorktreeRequest: {
      branch: string;
      start_point?: string | null;
    };
    DirEntry: {
      is_git_repo: boolean;
      name: string;
    };
    ListFilesResponse: {
      /** @description Subdirectories within `path`. */
      entries: components['schemas']['DirEntry'][];
      /** @description User's home directory (for quick-nav in UI). */
      home_dir?: string | null;
      /** @description Canonical absolute path of the listed directory. */
      path: string;
    };
    ListWorktreeStartPointsResponse: {
      default_start_point?: string | null;
      git_error?: string | null;
      start_points: components['schemas']['StartPoint'][];
    };
    ListWorktreesResponse: {
      git_error?: string | null;
      worktrees: components['schemas']['Worktree'][];
    };
    Project: {
      git_error?: string | null;
      id: string;
      name: string;
      path: string;
      /** Format: double */
      position?: number;
    };
    ReorderProjectsRequest: {
      project_ids: string[];
    };
    ReorderWorktreesRequest: {
      worktree_ids: string[];
    };
    ServerControlMessage:
      | {
          /** Format: int64 */
          byte_offset: number;
          data_lost: boolean;
          /** @enum {string} */
          type: 'attached';
        }
      | {
          /** @enum {string} */
          type: 'tab_closed';
        };
    Settings: {
      appearance?: null | components['schemas']['AppearanceSettings'];
      terminal?: null | components['schemas']['TerminalSettings'];
      worktree?: null | components['schemas']['WorktreeSettings'];
    };
    StartPoint: {
      local_ref?: string | null;
      remote_refs: string[];
      sha: string;
      value: string;
    };
    /**
     * @description Serializable tab metadata. Sent to clients via REST
     *     and SSE.
     */
    TabInfo: {
      /** Format: int64 */
      created_at: number;
      id: string;
      label: string;
      /** Format: double */
      position: number;
      session_id: string;
      type: string;
      worktree_id: string;
    };
    TerminalSettings: {
      bundledFont?: string;
      /** Format: int32 */
      fontSize?: number;
      fontSource?: string;
      systemFontFamily?: string;
    };
    ThemeFile: components['schemas']['ThemeMeta'] & {
      colors: {
        [key: string]: unknown;
      };
    };
    ThemeMeta: {
      id: string;
      name: string;
      type: string;
    };
    UpdateProjectRequest: {
      name?: string | null;
    };
    UpdateTabRequest: {
      label?: string | null;
      /** Format: double */
      position?: number | null;
    };
    Worktree: {
      branch: string;
      id: string;
      is_local: boolean;
      missing_on_disk?: boolean;
      name: string;
      path: string;
      /** Format: double */
      position: number;
      project_id: string;
    };
    WorktreeSettings: {
      locationMode?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  event_stream: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent event stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_files: {
    parameters: {
      query?: {
        /** @description Directory to list. Defaults to home dir. */
        path?: string;
        /** @description Whether to include dotfiles. Defaults to false. */
        show_hidden?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory listing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListFilesResponse'];
        };
      };
      /** @description Path is not a directory */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Directory not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  openapi_json: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenAPI document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'][];
        };
      };
    };
  };
  add_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddProjectRequest'];
      };
    };
    responses: {
      /** @description Project already exists */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description Project created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description Invalid path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderProjectsRequest'];
      };
    };
    responses: {
      /** @description Projects reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'][];
        };
      };
      /** @description Invalid order payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project: {
    parameters: {
      query?: {
        force?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid project path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project has dirty linked worktrees */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProjectRequest'];
      };
    };
    responses: {
      /** @description Project updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project worktrees */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListWorktreesResponse'];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_project_worktree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorktreeRequest'];
      };
    };
    responses: {
      /** @description Worktree created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Worktree'];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree creation conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderWorktreesRequest'];
      };
    };
    responses: {
      /** @description Worktrees reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Worktree'][];
        };
      };
      /** @description Invalid reorder payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktree_start_points: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Candidate worktree start points */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListWorktreeStartPointsResponse'];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project_worktree: {
    parameters: {
      query?: {
        force?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Worktree removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid worktree request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree has uncommitted changes */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Settings'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  save_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Settings'];
      };
    };
    responses: {
      /** @description Settings saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_tabs: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List tabs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TabInfo'][];
        };
      };
    };
  };
  create_tab: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTabRequest'];
      };
    };
    responses: {
      /** @description Tab created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TabInfo'];
        };
      };
      /** @description Worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tab removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTabRequest'];
      };
    };
    responses: {
      /** @description Tab updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TabInfo'];
        };
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ws_handler: {
    parameters: {
      query: {
        tab_id: string;
        /**
         * @description Byte offset for resumable reconnection. When
         *     present, the server only replays scrollback bytes
         *     the client missed.
         */
        resume_from?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket upgraded */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_themes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Theme metadata list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThemeMeta'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_theme: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ThemeFile'];
      };
    };
    responses: {
      /** @description Theme created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThemeMeta'];
        };
      };
      /** @description Theme already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_theme: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Theme ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Theme payload */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThemeFile'];
        };
      };
      /** @description Theme not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_theme: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Theme ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Theme removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Theme not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
