/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/editor-themes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/editor-themes — list all available editor themes. */
    get: operations["list_editor_themes"];
    put?: never;
    /** POST /api/editor-themes — upload a custom VS Code theme. */
    post: operations["upload_editor_theme"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/editor-themes/discover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/editor-themes/discover — scan local editors for theme extensions. */
    get: operations["discover_editor_themes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/editor-themes/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** POST /api/editor-themes/import — import a theme from an extension. */
    post: operations["import_extension_theme"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/editor-themes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/editor-themes/{id} — full theme data. */
    get: operations["get_editor_theme"];
    put?: never;
    post?: never;
    /** DELETE /api/editor-themes/{id} — delete a custom theme. */
    delete: operations["delete_editor_theme"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["event_stream"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_files"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the generated OpenAPI document as JSON. */
    get: operations["openapi_json"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_projects"];
    put?: never;
    post: operations["add_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_projects"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_project"];
    options?: never;
    head?: never;
    patch: operations["update_project"];
    trace?: never;
  };
  "/api/projects/{id}/worktrees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktrees"];
    put?: never;
    post: operations["create_project_worktree"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["import_project_worktree"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/importable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_importable_worktrees"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_project_worktrees"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/start-points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktree_start_points"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_project_worktree"];
    options?: never;
    head?: never;
    patch: operations["update_project_worktree"];
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_project_worktree_files"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/files/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_file_content"];
    put: operations["put_project_worktree_file_content"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/files/rename": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rename_project_worktree_file"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_git_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/commits/{commit_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_commit_details"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project_worktree_git_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/discard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["discard_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/rename-branch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rename_worktree_branch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/stage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["stage_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}/worktrees/{worktree_id}/git/unstage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["unstage_project_worktree_path"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GET /api/settings */
    get: operations["get_settings"];
    /** PUT /api/settings — full replace */
    put: operations["put_settings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** PATCH /api/settings — partial update */
    patch: operations["patch_settings"];
    trace?: never;
  };
  "/api/tabs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_tabs"];
    put?: never;
    post: operations["create_tab"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tabs/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["reorder_tabs"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tabs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_tab"];
    options?: never;
    head?: never;
    patch: operations["update_tab"];
    trace?: never;
  };
  "/api/terminal/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ws_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddProjectRequest: {
      path: string;
    };
    ApiErrorResponse: {
      message: string;
    };
    AppearanceSettings: {
      colorScheme?: components["schemas"]["ColorScheme"];
      darkTheme?: string;
      lightTheme?: string;
    };
    AppearanceSettingsPatch: {
      colorScheme?: null | components["schemas"]["ColorScheme"];
      darkTheme?: string | null;
      lightTheme?: string | null;
    };
    ClientControlMessage: {
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      /** @enum {string} */
      type: "resize";
      visible: boolean;
    };
    /** @enum {string} */
    ColorScheme: "auto" | "light" | "dark";
    CreateTabRequest:
      | {
          /** @enum {string} */
          type: "terminal";
          worktree_id: string;
        }
      | {
          path: string;
          preview?: boolean;
          /** @enum {string} */
          type: "file";
          worktree_id: string;
        }
      | {
          commit_id?: string | null;
          original_path?: string | null;
          path: string;
          preview?: boolean;
          scope: components["schemas"]["GitDiffScope"];
          /** @enum {string} */
          type: "git_diff";
          worktree_id: string;
        };
    CreateWorktreeRequest: {
      branch: string;
      source_ref?: string | null;
      start_point?: string | null;
    };
    DirEntry: {
      is_git_repo: boolean;
      name: string;
    };
    DiscoveredExtension: {
      displayName: string;
      extensionId: string;
      sourceEditor: string;
      themes: components["schemas"]["DiscoveredTheme"][];
      version: string;
    };
    DiscoveredTheme: {
      differs: boolean;
      installedId?: string | null;
      label: string;
      /**
       * @description Path to the theme JSON file, relative to the editor's extensions
       *     directory (e.g. "publisher.ext-1.0.0/themes/dark.json").
       */
      sourcePath: string;
      type: string;
    };
    EditorSettings: {
      darkEditorTheme?: string;
      lightEditorTheme?: string;
    };
    EditorSettingsPatch: {
      darkEditorTheme?: string | null;
      lightEditorTheme?: string | null;
    };
    EditorThemeEntry: {
      builtin: boolean;
      id: string;
      name: string;
      type: string;
    };
    GitCommitDetailsResponse: {
      author: components["schemas"]["GitCommitPerson"];
      committer: components["schemas"]["GitCommitPerson"];
      files: components["schemas"]["GitFileChange"][];
      id: string;
      message: string;
      short_id: string;
      summary: string;
    };
    GitCommitPerson: {
      date: string;
      email: string;
      name: string;
    };
    GitCommitSummary: {
      id: string;
      short_id: string;
      summary: string;
    };
    /** @enum {string} */
    GitDiffScope: "staged" | "unstaged" | "commit";
    GitFileChange: {
      change_type: components["schemas"]["GitFileChangeType"];
      deletions?: number | null;
      insertions?: number | null;
      original_path?: string | null;
      path: string;
    };
    /** @enum {string} */
    GitFileChangeType:
      | "added"
      | "copied"
      | "renamed"
      | "conflict"
      | "modified"
      | "deleted"
      | "typechange"
      | "untracked";
    ImportThemeRequest: {
      /** @description Display name for the imported theme. */
      label: string;
      overwriteId?: string | null;
      sourceEditor: string;
      /**
       * @description Path to the theme JSON file, relative to the editor's extensions
       *     directory. Must match a `source_path` from the discover response.
       */
      sourcePath: string;
      /** @description Theme type: "light" or "dark". */
      type: string;
    };
    ImportWorktreeRequest: {
      path: string;
    };
    ImportableWorktree: {
      branch?: string | null;
      id: string;
      path: string;
    };
    ListFilesResponse: {
      /** @description Subdirectories within `path`. */
      entries: components["schemas"]["DirEntry"][];
      /** @description User's home directory (for quick-nav in UI). */
      home_dir?: string | null;
      /** @description Canonical absolute path of the listed directory. */
      path: string;
    };
    ListImportableWorktreesResponse: {
      git_error?: string | null;
      importable_worktrees: components["schemas"]["ImportableWorktree"][];
    };
    ListWorktreeFilesResponse: {
      entries: components["schemas"]["WorktreeFileEntry"][];
      /** Format: int32 */
      generation: number;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    ListWorktreeStartPointsResponse: {
      default_start_point?: string | null;
      git_error?: string | null;
      start_points: components["schemas"]["StartPoint"][];
    };
    ListWorktreesResponse: {
      git_error?: string | null;
      worktrees: components["schemas"]["Worktree"][];
    };
    Project: {
      git_error?: string | null;
      id: string;
      name: string;
      path: string;
      /** Format: double */
      position?: number;
    };
    RenameWorktreeBranchRequest: {
      new_branch: string;
    };
    RenameWorktreeFileRequest: {
      /** @description New basename for the file or directory. */
      new_name: string;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    RenameWorktreeFileResponse: {
      /** @description Updated relative path from the worktree root. */
      path: string;
    };
    ReorderProjectsRequest: {
      project_ids: string[];
    };
    ReorderTabsRequest: {
      tab_ids: string[];
      worktree_id: string;
    };
    ReorderWorktreesRequest: {
      worktree_ids: string[];
    };
    ServerControlMessage:
      | {
          /** Format: int64 */
          byte_offset: number;
          /** Format: int32 */
          cols: number;
          data_lost: boolean;
          /** Format: int32 */
          rows: number;
          snapshot: boolean;
          /** @enum {string} */
          type: "attached";
        }
      | {
          /** Format: int32 */
          cols: number;
          /** Format: int32 */
          rows: number;
          /** @enum {string} */
          type: "pty_resized";
        }
      | {
          /** @enum {string} */
          type: "tab_closed";
        };
    Settings: {
      appearance?: components["schemas"]["AppearanceSettings"];
      editor?: components["schemas"]["EditorSettings"];
      terminal?: components["schemas"]["TerminalSettings"];
      worktree?: components["schemas"]["WorktreeSettings"];
    };
    SettingsPatch: {
      appearance?: null | components["schemas"]["AppearanceSettingsPatch"];
      editor?: null | components["schemas"]["EditorSettingsPatch"];
      terminal?: null | components["schemas"]["TerminalSettingsPatch"];
      worktree?: null | components["schemas"]["WorktreeSettingsPatch"];
    };
    SettingsState: {
      generation: string;
      settings: components["schemas"]["Settings"];
      status: components["schemas"]["SettingsStatus"];
    };
    SettingsStatus: {
      kind: components["schemas"]["SettingsStatusKind"];
      message?: string | null;
      writesBlocked: boolean;
    };
    /** @enum {string} */
    SettingsStatusKind: "ok" | "invalidFile";
    StartPoint: {
      local_ref?: string | null;
      remote_refs: string[];
      sha: string;
      value: string;
    };
    TabInfo:
      | {
          /** Format: int64 */
          created_at: number;
          has_notification?: boolean;
          id: string;
          label: string;
          /** Format: double */
          position: number;
          preview: boolean;
          session_id: string;
          /** @enum {string} */
          type: "terminal";
          worktree_id: string;
        }
      | {
          /** Format: int64 */
          created_at: number;
          id: string;
          label: string;
          path: string;
          /** Format: double */
          position: number;
          preview: boolean;
          session_id: string;
          /** @enum {string} */
          type: "file";
          worktree_id: string;
        }
      | {
          commit_id?: string | null;
          /** Format: int64 */
          created_at: number;
          id: string;
          label: string;
          original_path?: string | null;
          path: string;
          /** Format: double */
          position: number;
          preview: boolean;
          scope: components["schemas"]["GitDiffScope"];
          session_id: string;
          /** @enum {string} */
          type: "git_diff";
          worktree_id: string;
        };
    /** @enum {string} */
    TerminalFontSource: "default" | "system" | "bundled";
    TerminalSettings: {
      bundledFont?: string;
      /** Format: int32 */
      fontSize?: number;
      fontSource?: components["schemas"]["TerminalFontSource"];
      systemFontFamily?: string;
    };
    TerminalSettingsPatch: {
      bundledFont?: string | null;
      /** Format: int32 */
      fontSize?: number | null;
      fontSource?: null | components["schemas"]["TerminalFontSource"];
      systemFontFamily?: string | null;
    };
    UpdateProjectRequest: {
      name?: string | null;
    };
    UpdateTabRequest: {
      has_notification?: boolean | null;
      label?: string | null;
      /** Format: double */
      position?: number | null;
      preview?: boolean | null;
    };
    UpdateWorktreeRequest: {
      name?: string | null;
      source_ref?: string | null;
      ui_mode?: null | components["schemas"]["WorktreeUiMode"];
    };
    VscodeThemeJson: {
      colors?: {
        [key: string]: string;
      };
      name?: string;
      tokenColors?: components["schemas"]["VscodeTokenColor"][];
      type?: string | null;
    };
    VscodeTokenColor: {
      name?: string | null;
      scope?: null | components["schemas"]["VscodeTokenScope"];
      settings: components["schemas"]["VscodeTokenColorSettings"];
    };
    VscodeTokenColorSettings: {
      background?: string | null;
      fontStyle?: string | null;
      foreground?: string | null;
    };
    /** @description A scope can be a single string or an array of strings. */
    VscodeTokenScope: string | string[];
    Worktree: {
      branch: string;
      id: string;
      is_imported?: boolean;
      is_local: boolean;
      missing_on_disk?: boolean;
      name: string;
      path: string;
      /** Format: double */
      position: number;
      project_id: string;
      source_ref?: string | null;
      ui_mode: components["schemas"]["WorktreeUiMode"];
    };
    WorktreeFileContentParams: {
      /** @description Relative path from the worktree root. */
      path: string;
    };
    WorktreeFileContentResponse: {
      content: string;
      language: string;
      path: string;
      read_only: boolean;
      unsupported_reason?: string | null;
      version_token: string;
    };
    WorktreeFileEntry: {
      is_symlink: boolean;
      kind: components["schemas"]["WorktreeFileKind"];
      name: string;
      path: string;
    };
    /** @enum {string} */
    WorktreeFileKind: "directory" | "file";
    WorktreeGitDiffParams: {
      commit_id?: string | null;
      /** @description Original relative path for rename/copy actions. */
      original_path?: string | null;
      /** @description Relative path from the worktree root. */
      path: string;
      scope: components["schemas"]["GitDiffScope"];
    };
    WorktreeGitDiffResponse: {
      commit_id?: string | null;
      language: string;
      left_content: string;
      left_label: string;
      modified_version_token?: string | null;
      original_path?: string | null;
      path: string;
      read_only: boolean;
      right_content: string;
      right_label: string;
      scope: components["schemas"]["GitDiffScope"];
      unsupported_reason?: string | null;
    };
    WorktreeGitPathActionRequest: {
      /** @description Original relative path for rename/copy actions. */
      original_path?: string | null;
      /** @description Relative path from the worktree root. */
      path: string;
    };
    WorktreeGitStatusResponse: {
      ahead_commits: components["schemas"]["GitCommitSummary"][];
      ahead_count: number;
      comparison_available: boolean;
      comparison_error?: string | null;
      /** Format: int32 */
      generation: number;
      source_ref?: string | null;
      staged_files: components["schemas"]["GitFileChange"][];
      unstaged_files: components["schemas"]["GitFileChange"][];
    };
    /** @enum {string} */
    WorktreeLocationMode: "dataDir" | "repoLocalDotHubris";
    WorktreeSettings: {
      locationMode?: components["schemas"]["WorktreeLocationMode"];
    };
    WorktreeSettingsPatch: {
      locationMode?: null | components["schemas"]["WorktreeLocationMode"];
    };
    /** @enum {string} */
    WorktreeUiMode: "hubris" | "vscode";
    WriteWorktreeFileContentRequest: {
      content: string;
      expected_version_token: string;
      path: string;
    };
    WriteWorktreeFileContentResponse: {
      path: string;
      version_token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_editor_themes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Editor theme list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditorThemeEntry"][];
        };
      };
    };
  };
  upload_editor_theme: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VscodeThemeJson"];
      };
    };
    responses: {
      /** @description Theme created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditorThemeEntry"];
        };
      };
      /** @description Invalid theme JSON */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  discover_editor_themes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Discovered extension themes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DiscoveredExtension"][];
        };
      };
    };
  };
  import_extension_theme: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportThemeRequest"];
      };
    };
    responses: {
      /** @description Theme imported */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EditorThemeEntry"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Extension or theme not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_editor_theme: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Theme ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Theme data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VscodeThemeJson"];
        };
      };
      /** @description Theme not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_editor_theme: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Theme ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Theme deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot delete built-in theme */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Theme not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  event_stream: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent event stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_files: {
    parameters: {
      query?: {
        /** @description Directory to list. Defaults to home dir. */
        path?: string;
        /** @description Whether to include dotfiles. Defaults to false. */
        show_hidden?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory listing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListFilesResponse"];
        };
      };
      /** @description Path is not a directory */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Directory not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  openapi_json: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenAPI document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  add_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddProjectRequest"];
      };
    };
    responses: {
      /** @description Project already exists */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Project created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Invalid path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderProjectsRequest"];
      };
    };
    responses: {
      /** @description Projects reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
      /** @description Invalid order payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project: {
    parameters: {
      query?: {
        force?: boolean;
        delete_managed_worktrees?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid project path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project has dirty or busy managed worktrees */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectRequest"];
      };
    };
    responses: {
      /** @description Project updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project worktrees */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreesResponse"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_project_worktree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorktreeRequest"];
      };
    };
    responses: {
      /** @description Worktree created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree creation conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  import_project_worktree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportWorktreeRequest"];
      };
    };
    responses: {
      /** @description Worktree imported */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"];
        };
      };
      /** @description Invalid request or path is not a worktree */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree already managed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_importable_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Importable worktrees */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListImportableWorktreesResponse"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_project_worktrees: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderWorktreesRequest"];
      };
    };
    responses: {
      /** @description Worktrees reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"][];
        };
      };
      /** @description Invalid reorder payload */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktree_start_points: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Candidate worktree start points */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreeStartPointsResponse"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project_worktree: {
    parameters: {
      query?: {
        force?: boolean;
        untrack_only?: boolean;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Worktree removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid worktree request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Worktree has uncommitted changes */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_project_worktree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorktreeRequest"];
      };
    };
    responses: {
      /** @description Worktree updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"];
        };
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_project_worktree_files: {
    parameters: {
      query?: {
        /** @description Relative path from the worktree root. Empty means root. */
        path?: string;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List immediate children for a worktree-relative directory */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListWorktreeFilesResponse"];
        };
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or directory not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_file_content: {
    parameters: {
      query: {
        /** @description Relative path from the worktree root. */
        path: string;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Load editable worktree file content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorktreeFileContentResponse"];
        };
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Project, worktree, or file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  put_project_worktree_file_content: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteWorktreeFileContentRequest"];
      };
    };
    responses: {
      /** @description Save editable worktree file content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WriteWorktreeFileContentResponse"];
        };
      };
      /** @description Invalid path or unsupported file */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Project, worktree, or file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Version conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  rename_project_worktree_file: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameWorktreeFileRequest"];
      };
    };
    responses: {
      /** @description Rename a file or directory within the worktree */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RenameWorktreeFileResponse"];
        };
      };
      /** @description Invalid relative path or new name */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Target path already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_git_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Git status for a worktree */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorktreeGitStatusResponse"];
        };
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_commit_details: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
        /** @description Commit SHA */
        commit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit details for a worktree commit */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GitCommitDetailsResponse"];
        };
      };
      /** @description Project, worktree, or commit not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_worktree_git_diff: {
    parameters: {
      query: {
        /** @description Relative path from the worktree root. */
        path: string;
        scope: components["schemas"]["GitDiffScope"];
        /** @description Original relative path for rename/copy actions. */
        original_path?: string;
        commit_id?: string;
      };
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Load a staged, unstaged, or commit file diff */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorktreeGitDiffResponse"];
        };
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  discard_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Worktree changes discarded for the path */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rename_worktree_branch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameWorktreeBranchRequest"];
      };
    };
    responses: {
      /** @description Branch renamed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Worktree"];
        };
      };
      /** @description Invalid branch name */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project or worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  stage_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Path staged */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unstage_project_worktree_path: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
        /** @description Worktree ID */
        worktree_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorktreeGitPathActionRequest"];
      };
    };
    responses: {
      /** @description Path unstaged */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid relative path */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project, worktree, or path not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  put_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      /** @description Settings saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Settings file is invalid on disk */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patch_settings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description Settings patched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SettingsState"];
        };
      };
      /** @description Settings file is invalid on disk */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_tabs: {
    parameters: {
      query?: {
        session_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List tabs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"][];
        };
      };
    };
  };
  create_tab: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTabRequest"];
      };
    };
    responses: {
      /** @description Tab created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"];
        };
      };
      /** @description Worktree not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_tabs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderTabsRequest"];
      };
    };
    responses: {
      /** @description Tabs reordered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"][];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tab removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_tab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tab ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTabRequest"];
      };
    };
    responses: {
      /** @description Tab updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TabInfo"];
        };
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ws_handler: {
    parameters: {
      query: {
        tab_id: string;
        /**
         * @description Byte offset for resumable reconnection. When
         *     present, the server only replays scrollback bytes
         *     the client missed.
         */
        resume_from?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket upgraded */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
