// Generated file. Do not edit.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitDiffScope = "staged" | "unstaged";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabInfo =
  | {
      type: "terminal";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
    }
  | {
      type: "file";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
    }
  | {
      type: "git_diff";
      id: string;
      session_id: string;
      worktree_id: string;
      label: string;
      position: number;
      created_at: number;
      preview: boolean;
      path: string;
      scope: GitDiffScope;
      original_path: string | null;
    };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = {
  id: string;
  name: string;
  path: string;
  position: number;
  git_error?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = {
  id: string;
  project_id: string;
  name: string;
  path: string;
  branch: string;
  source_ref: string | null;
  is_local: boolean;
  missing_on_disk: boolean;
  position: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorScheme = "auto" | "light" | "dark";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalFontSource = "default" | "system" | "bundled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeLocationMode = "dataDir" | "repoLocalDotHubris";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = {
  colorScheme: ColorScheme;
  lightTheme: string;
  darkTheme: string;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = {
  fontSource: TerminalFontSource;
  systemFontFamily: string;
  bundledFont: string;
  fontSize: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeSettings = { locationMode: WorktreeLocationMode };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
  appearance: AppearanceSettings;
  terminal: TerminalSettings;
  worktree: WorktreeSettings;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatusKind = "ok" | "invalidFile";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsStatus = {
  kind: SettingsStatusKind;
  writesBlocked: boolean;
  message: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsState = {
  settings: Settings;
  generation: string;
  status: SettingsStatus;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventKind =
  | {
      type: "snapshot";
      data: {
        tabs: Array<TabInfo>;
        projects: Array<Project>;
        worktrees: { [key in string]: Array<Worktree> };
        project_errors: { [key in string]: string };
        settings: Settings;
        settings_generation: string;
        settings_status: SettingsStatus;
      };
    }
  | { type: "tab_created"; data: { session_id: string; tab: TabInfo } }
  | { type: "tab_closed"; data: { session_id: string; tab_id: string } }
  | { type: "tab_updated"; data: { session_id: string; tab: TabInfo } }
  | {
      type: "tabs_reordered";
      data: { session_id: string; worktree_id: string; tabs: Array<TabInfo> };
    }
  | { type: "project_added"; data: Project }
  | { type: "project_removed"; data: { project_id: string } }
  | { type: "project_updated"; data: Project }
  | { type: "projects_reordered"; data: Array<Project> }
  | { type: "worktree_created"; data: Worktree }
  | {
      type: "worktree_deleted";
      data: { project_id: string; worktree_id: string };
    }
  | {
      type: "worktrees_reordered";
      data: { project_id: string; worktrees: Array<Worktree> };
    }
  | {
      type: "project_worktrees_updated";
      data: {
        project_id: string;
        worktrees: Array<Worktree>;
        git_error: string | null;
      };
    }
  | {
      type: "worktree_files_updated";
      data: {
        project_id: string;
        worktree_id: string;
        generation: number;
        changed_paths: Array<string>;
        listing_paths: Array<string>;
      };
    }
  | {
      type: "worktree_git_status_updated";
      data: { project_id: string; worktree_id: string; generation: number };
    }
  | { type: "settings_updated"; data: SettingsState };
