// Generated file. Do not edit.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable tab metadata. Sent to clients via REST
 * and SSE.
 */
export type TabInfo = {
  id: string;
  session_id: string;
  worktree_id: string;
  label: string;
  type: string;
  position: number;
  created_at: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = {
  id: string;
  name: string;
  path: string;
  position: number;
  git_error?: string | null;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Worktree = {
  id: string;
  project_id: string;
  name: string;
  path: string;
  branch: string;
  is_local: boolean;
  missing_on_disk: boolean;
  position: number;
};

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventKind =
  | {
      type: 'snapshot';
      data: {
        tabs: Array<TabInfo>;
        projects: Array<Project>;
        worktrees: { [key in string]: Array<Worktree> };
        project_errors: { [key in string]: string };
      };
    }
  | { type: 'tab_created'; data: TabInfo }
  | { type: 'tab_closed'; data: { tab_id: string } }
  | { type: 'tab_updated'; data: TabInfo }
  | { type: 'project_added'; data: Project }
  | { type: 'project_removed'; data: { project_id: string } }
  | { type: 'project_updated'; data: Project }
  | { type: 'projects_reordered'; data: Array<Project> }
  | { type: 'worktree_created'; data: Worktree }
  | {
      type: 'worktree_deleted';
      data: { project_id: string; worktree_id: string };
    }
  | {
      type: 'worktrees_reordered';
      data: { project_id: string; worktrees: Array<Worktree> };
    }
  | {
      type: 'project_worktrees_updated';
      data: {
        project_id: string;
        worktrees: Array<Worktree>;
        git_error: string | null;
      };
    };
